In [1]:
import torch

## Vanilla Self Attention:

### The inputs are given below

In [2]:
inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

In [3]:
query = inputs[0]
print(query)

tensor([0.4300, 0.1500, 0.8900])


### Calculating attention vectors

In [4]:
dp = {}
def calculate_dot_product(i, inputs):
    dot_products = []
    for j in range(len(inputs)):
        dot_products.append(torch.dot(inputs[i], inputs[j]))
    return dot_products
for i in range(len(inputs)):
    dp[i] = calculate_dot_product(i, inputs)
print(dp)

{0: [tensor(0.9995), tensor(0.9544), tensor(0.9422), tensor(0.4753), tensor(0.4576), tensor(0.6310)], 1: [tensor(0.9544), tensor(1.4950), tensor(1.4754), tensor(0.8434), tensor(0.7070), tensor(1.0865)], 2: [tensor(0.9422), tensor(1.4754), tensor(1.4570), tensor(0.8296), tensor(0.7154), tensor(1.0605)], 3: [tensor(0.4753), tensor(0.8434), tensor(0.8296), tensor(0.4937), tensor(0.3474), tensor(0.6565)], 4: [tensor(0.4576), tensor(0.7070), tensor(0.7154), tensor(0.3474), tensor(0.6654), tensor(0.2935)], 5: [tensor(0.6310), tensor(1.0865), tensor(1.0605), tensor(0.6565), tensor(0.2935), tensor(0.9450)]}


### Calculating normalized attention vectors

In [5]:
def torch_softmax(x):
    return torch.exp(x) / torch.sum(torch.exp(x), dim=0)
for element in dp:
    dp[element] = torch_softmax(torch.tensor(dp[element]))
print(dp)

{0: tensor([0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452]), 1: tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581]), 2: tensor([0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565]), 3: tensor([0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720]), 4: tensor([0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295]), 5: tensor([0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896])}


### Calculating context vectors:

In [6]:
def calculate_context_vector(dp_element, inputs):
    context_vector = torch.matmul(dp_element,inputs)
    return context_vector
for element in dp:
    dp[element] = calculate_context_vector(dp[element], inputs)
print(dp)

{0: tensor([0.4421, 0.5931, 0.5790]), 1: tensor([0.4419, 0.6515, 0.5683]), 2: tensor([0.4431, 0.6496, 0.5671]), 3: tensor([0.4304, 0.6298, 0.5510]), 4: tensor([0.4671, 0.5910, 0.5266]), 5: tensor([0.4177, 0.6503, 0.5645])}


### In Matrix form 

In [7]:
inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

attn_scores = torch.empty(6, 6)
for i, x_i in enumerate(inputs):
    for j, x_j in enumerate(inputs):

      attn_scores[i, j] = torch.dot(x_i, x_j)
print(attn_scores)


tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [8]:
attn_socres = inputs@inputs.T
print(attn_scores)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [9]:
attn_weights = torch.softmax(attn_scores, dim=-1)
# dim = -1 means normalize across the columns so that sum of each row is 1
print(attn_weights)
print(attn_weights.sum(dim=-1))

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])
tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])


In [10]:
context_vectors = attn_weights@inputs
print(context_vectors)

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])


In [11]:
def self_attention(inputs):
    attn_scores = inputs@inputs.T
    attn_weights = torch.softmax(attn_scores, dim = -1)
    context_vectors = attn_weights@inputs
    return context_vectors
print(self_attention(inputs))

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])


## Self attention as in Transformer architecture

In [12]:
inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

In [13]:
x1 = inputs[0]
d_in = inputs.shape[1]
d_out = 2

In [14]:
torch.manual_seed(0)
W_query = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad = False)
W_key = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad = False)
W_value = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad = False)


In [15]:
W_query

Parameter containing:
tensor([[0.4963, 0.7682],
        [0.0885, 0.1320],
        [0.3074, 0.6341]])

In [19]:
# if we want to calculate attention weigths for x1, then also we need keys and values for all
#  the inputs as they are involved in the calculation of attention weights for x1
query = x1@W_query
keys = inputs@W_key
values= inputs@W_value
print(query)

tensor([0.5003, 0.9145])


In [16]:
inputs@W_query  
# All the queries shown here. But only one is used here as we are looking at context vector 
# of inputs[1] or second input word.

tensor([[0.5003, 0.9145],
        [0.5528, 0.9559],
        [0.5548, 0.9559],
        [0.2619, 0.4548],
        [0.4350, 0.6879],
        [0.2647, 0.4928]])

In [20]:
keys

tensor([[0.5896, 0.8378],
        [0.8962, 1.3083],
        [0.8899, 1.3055],
        [0.4872, 0.6965],
        [0.5262, 0.8885],
        [0.5809, 0.7716]])

In [21]:
keys_1 = keys[0]
attn_scores_1 = query.dot(keys_1)
print(attn_scores_1)
# attention score of first element with respect to second element

tensor(1.0611)


In [23]:
attn_scores_1 = query@keys.T
print(attn_scores_1)
# attention score of all elements with respect to the second element(query)

tensor([1.0611, 1.6447, 1.6391, 0.8807, 1.0757, 0.9962])


In [24]:
d_k = keys.shape[-1]
attn_weights_1 = torch.softmax(attn_scores_1/ d_k**0.5, dim = -1)
print(attn_weights_1)

tensor([0.1457, 0.2202, 0.2193, 0.1283, 0.1473, 0.1392])


In [25]:
context_vectors_1 = attn_weights_1@values
print(context_vectors_1)

tensor([0.5762, 0.8392])


### Self attention class (v1 -> without masking)

In [44]:
import torch.nn as nn
class SelfAttention(nn.Module):
    def __init__(self, d_in, d_out):
        super().__init__()
        self.d_out = d_out
        self.W_query = nn.Parameter(torch.rand(d_in, d_out), requires_grad = False)
        self.W_key = nn.Parameter(torch.rand(d_in, d_out), requires_grad = False)
        self.W_value = nn.Parameter(torch.rand(d_in, d_out), requires_grad = False)
    def forward(self, x):
        keys = x@self.W_key
        values = x@self.W_value
        query = x@self.W_query
        attn_scores = query@keys.T
        d_k = keys.shape[-1]
        attn_weights = torch.softmax(attn_scores/d_k**0.5, dim = -1)
        context_vec = attn_weights@values
        return context_vec
    

In [45]:
torch.manual_seed(123)
attn_vec = SelfAttention(d_in, d_out)
print(attn_vec(inputs))

tensor([[0.2996, 0.8053],
        [0.3061, 0.8210],
        [0.3058, 0.8203],
        [0.2948, 0.7939],
        [0.2927, 0.7891],
        [0.2990, 0.8040]])


Using nn.Linear Layers -> nn.Linear has an optimized weight initialization scheme which is more stable and effective in training.

In [46]:
class SelfAttention_v2(nn.Module):
    def __init__(self, d_in, d_out, qkv_bias=False):
        super().__init__()
        self.d_out = d_out
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key   = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)
 
    def forward(self, x):
        keys = self.W_key(x)
        queries = self.W_query(x)
        values = self.W_value(x)
        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(attn_scores / keys.shape[-1]**0.5, dim=-1)
        context_vec = attn_weights @ values
        return context_vec

In [47]:
torch.manual_seed(123)
attn_vec = SelfAttention_v2(d_in, d_out)
print(attn_vec(inputs))

tensor([[-0.5337, -0.1051],
        [-0.5323, -0.1080],
        [-0.5323, -0.1079],
        [-0.5297, -0.1076],
        [-0.5311, -0.1066],
        [-0.5299, -0.1081]], grad_fn=<MmBackward0>)


### Masked Self Attention

In [48]:
query = attn_vec.W_query(inputs)
keys = attn_vec.W_key(inputs)
values = attn_vec.W_value(inputs)
attn_scores = query@keys.T
attn_weights = torch.softmax(attn_scores/keys.shape[-1]**0.5, dim = -1)
print(attn_weights)

tensor([[0.1717, 0.1762, 0.1761, 0.1555, 0.1627, 0.1579],
        [0.1636, 0.1749, 0.1746, 0.1612, 0.1605, 0.1652],
        [0.1637, 0.1749, 0.1746, 0.1611, 0.1606, 0.1651],
        [0.1636, 0.1704, 0.1702, 0.1652, 0.1632, 0.1674],
        [0.1667, 0.1722, 0.1721, 0.1618, 0.1633, 0.1639],
        [0.1624, 0.1709, 0.1706, 0.1654, 0.1625, 0.1682]],
       grad_fn=<SoftmaxBackward0>)


In [49]:
context_length = attn_scores.shape[0]
mask_simple = torch.tril(torch.ones(context_length, context_length))
print(mask_simple)

tensor([[1., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1.]])


In [50]:
masked_simple = attn_weights*mask_simple
masked_simple

tensor([[0.1717, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1636, 0.1749, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1637, 0.1749, 0.1746, 0.0000, 0.0000, 0.0000],
        [0.1636, 0.1704, 0.1702, 0.1652, 0.0000, 0.0000],
        [0.1667, 0.1722, 0.1721, 0.1618, 0.1633, 0.0000],
        [0.1624, 0.1709, 0.1706, 0.1654, 0.1625, 0.1682]],
       grad_fn=<MulBackward0>)

In [51]:
row_sums = masked_simple.sum(dim = 1, keepdim = True)
masked_simple_norm = masked_simple/row_sums
masked_simple_norm


tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4833, 0.5167, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3190, 0.3408, 0.3402, 0.0000, 0.0000, 0.0000],
        [0.2445, 0.2545, 0.2542, 0.2468, 0.0000, 0.0000],
        [0.1994, 0.2060, 0.2058, 0.1935, 0.1953, 0.0000],
        [0.1624, 0.1709, 0.1706, 0.1654, 0.1625, 0.1682]],
       grad_fn=<DivBackward0>)

mask with -infinty

In [55]:
torch.exp(torch.tensor(-torch.inf))

tensor(0.)

In [52]:
mask_simple = torch.triu(torch.ones(context_length, context_length), diagonal = 1)
masked = attn_scores.masked_fill(mask_simple.bool(), -torch.inf)
print(mask_simple)
print(masked)

tensor([[0., 1., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0.3111,   -inf,   -inf,   -inf,   -inf,   -inf],
        [0.1655, 0.2602,   -inf,   -inf,   -inf,   -inf],
        [0.1667, 0.2602, 0.2577,   -inf,   -inf,   -inf],
        [0.0510, 0.1080, 0.1064, 0.0643,   -inf,   -inf],
        [0.1415, 0.1875, 0.1863, 0.0987, 0.1121,   -inf],
        [0.0476, 0.1192, 0.1171, 0.0731, 0.0477, 0.0966]],
       grad_fn=<MaskedFillBackward0>)


In [56]:
attn_weights = torch.softmax(masked/keys.shape[0]**0.5, dim = -1)
print(attn_weights)

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4903, 0.5097, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3250, 0.3377, 0.3373, 0.0000, 0.0000, 0.0000],
        [0.2468, 0.2526, 0.2524, 0.2481, 0.0000, 0.0000],
        [0.1997, 0.2035, 0.2034, 0.1962, 0.1973, 0.0000],
        [0.1642, 0.1691, 0.1690, 0.1659, 0.1642, 0.1675]],
       grad_fn=<SoftmaxBackward0>)


In [57]:
context_vec = attn_weights@values
print(context_vec)

tensor([[-0.4519,  0.2216],
        [-0.5856,  0.0087],
        [-0.6284, -0.0607],
        [-0.5664, -0.0832],
        [-0.5511, -0.0978],
        [-0.5290, -0.1073]], grad_fn=<MmBackward0>)


mask with dropout

In [59]:
torch.manual_seed(123)
dropout = nn.Dropout(0.5)
print(torch.ones(6,6))
print(dropout(torch.ones(6,6)))

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
tensor([[2., 2., 0., 2., 2., 0.],
        [0., 0., 0., 2., 0., 2.],
        [2., 2., 2., 2., 0., 2.],
        [0., 2., 2., 0., 0., 2.],
        [0., 2., 0., 2., 0., 2.],
        [0., 2., 2., 2., 2., 0.]])


2 is coming because of the formula used internally in dropout -> 1 / 1 - dropout_rate

In [60]:
dropout_attn_weights = dropout(attn_weights)
print(dropout_attn_weights)

tensor([[2.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.6753, 0.6746, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.5049, 0.4963, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.3946, 0.0000],
        [0.3285, 0.3382, 0.0000, 0.3319, 0.3285, 0.3351]],
       grad_fn=<MulBackward0>)


In [61]:
context_vec = dropout_attn_weights@values
print(context_vec)

tensor([[-0.9038,  0.4432],
        [ 0.0000,  0.0000],
        [-0.9631, -0.2654],
        [-0.5489, -0.1768],
        [-0.1918, -0.0630],
        [-0.8172, -0.1479]], grad_fn=<MmBackward0>)


### Causal Attention class

In [75]:
class CausalAttention(nn.Module):
    def __init__(self, d_in, d_out, qkv_bias, drop_rate):
        super().__init__()
        self.d_in = d_in
        self.d_out = d_out
        self.W_query = nn.Linear(d_in, d_out, bias = qkv_bias)
        self.W_keys = nn.Linear(d_in, d_out, bias = qkv_bias)
        self.W_values = nn.Linear(d_in, d_out, bias = qkv_bias)
        self.dropout = nn.Dropout(drop_rate)
        self.register_buffer('mask', torch.triu(torch.ones(inputs.shape[0], inputs.shape[0]), diagonal = 1))

    def forward(self, x):
        query = self.W_query(x)
        keys = self.W_keys(x)
        values = self.W_values(x)
        d_k = keys.shape[-1]
        attn_scores = query@keys.T
        attn_scores = attn_scores.masked_fill(self.mask.bool(), -torch.inf)
        attn_weights = torch.softmax(attn_scores/d_k**0.5, dim = -1)
        dropout_attn_weights = self.dropout(attn_weights)
        context_vec = dropout_attn_weights@values
        return context_vec

In [76]:
inputs

tensor([[0.4300, 0.1500, 0.8900],
        [0.5500, 0.8700, 0.6600],
        [0.5700, 0.8500, 0.6400],
        [0.2200, 0.5800, 0.3300],
        [0.7700, 0.2500, 0.1000],
        [0.0500, 0.8000, 0.5500]])

In [77]:
torch.manual_seed(123)
attn_vec = CausalAttention(d_in = 3, d_out = 2, qkv_bias = False, drop_rate = 0.5)
print(attn_vec(inputs))

tensor([[-0.9038,  0.4432],
        [-0.4368,  0.2142],
        [-0.4849, -0.1341],
        [-0.5834,  0.0081],
        [-0.6219, -0.0526],
        [-0.1417, -0.0505]], grad_fn=<MmBackward0>)


Using it in batch

In [78]:
class CausalAttention(nn.Module):
    def __init__(self, d_in, d_out, context_length, dropout, qkv_bias = False):
        super().__init__()
        self.W_query = nn.Linear(d_in, d_out, bias = qkv_bias)
        self.W_key = nn.Linear(d_in, d_out, bias = qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias = qkv_bias)
        self.dropout = nn.Dropout(dropout)
        self.register_buffer('mask', torch.triu(torch.ones(context_length, context_length), diagonal = 1))
    def forward(self, x):
        b, num_tokens, d_in = x.shape  # input tensor ->[batchsize, num_tokens, input_embedding_shape]
        keys = self.W_key(x)
        queries = self.W_query(x)
        values = self.W_value(x)
        attn_scores = queries @ keys.transpose(1,2)
        attn_scores.masked_fill(self.mask.bool()[:num_tokens,:num_tokens], -torch.inf)

        attn_weights = torch.softmax(attn_scores/keys.shape[-1]**0.5, dim = -1)
        attn_weights = self.dropout(attn_weights)
        context_vec = attn_weights@values
        return context_vec



In [79]:
torch.manual_seed(123)
batch = torch.stack((inputs, inputs), dim = 0)
context_length = batch.shape[1]
ca = CausalAttention(d_in, d_out, context_length, 0.0)
context_vec = ca(batch)
context_vec, context_vec.shape

(tensor([[[-0.5337, -0.1051],
          [-0.5323, -0.1080],
          [-0.5323, -0.1079],
          [-0.5297, -0.1076],
          [-0.5311, -0.1066],
          [-0.5299, -0.1081]],
 
         [[-0.5337, -0.1051],
          [-0.5323, -0.1080],
          [-0.5323, -0.1079],
          [-0.5297, -0.1076],
          [-0.5311, -0.1066],
          [-0.5299, -0.1081]]], grad_fn=<UnsafeViewBackward0>),
 torch.Size([2, 6, 2]))

## Multi-head Attention:

In [87]:
class MultiHeadAttentionWrapper(nn.Module):
    def __init__(self, d_in, d_out, context_length, dropout, num_heads, qkv_bias = False):
        super().__init__()
        assert (d_out % num_heads == 0), "Not divisble"
        self.heads = nn.ModuleList(
            [CausalAttention(d_in, d_out, context_length, dropout, qkv_bias) 
             for _ in range(num_heads)]
        )
    def forward(self, x):
        return torch.cat([head(x) for head in self.heads], dim = -1)


In [91]:
torch.manual_seed(123)
context_length = inputs.shape[0]
d_in, d_out = 3,2
mha = MultiHeadAttentionWrapper(d_in, d_out, context_length, 0.0, num_heads = 2)
context_vecs = mha(batch)

In [92]:
print(context_vecs, context_vecs.shape)

tensor([[[-0.5337, -0.1051,  0.5085,  0.3508],
         [-0.5323, -0.1080,  0.5084,  0.3508],
         [-0.5323, -0.1079,  0.5084,  0.3506],
         [-0.5297, -0.1076,  0.5074,  0.3471],
         [-0.5311, -0.1066,  0.5076,  0.3446],
         [-0.5299, -0.1081,  0.5077,  0.3493]],

        [[-0.5337, -0.1051,  0.5085,  0.3508],
         [-0.5323, -0.1080,  0.5084,  0.3508],
         [-0.5323, -0.1079,  0.5084,  0.3506],
         [-0.5297, -0.1076,  0.5074,  0.3471],
         [-0.5311, -0.1066,  0.5076,  0.3446],
         [-0.5299, -0.1081,  0.5077,  0.3493]]], grad_fn=<CatBackward0>) torch.Size([2, 6, 4])


### Parallel Calculation of Attention Heads

In [104]:
class MultiHeadAttention(nn.Module):
    def __init__(self, d_in, d_out, num_heads, context_length, dropout, qkv_bias = False):
        super().__init__()
        self.W_query = nn.Linear(d_in, d_out, bias = qkv_bias)
        self.W_key = nn.Linear(d_in, d_out, bias = qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias = qkv_bias)
        self.num_heads = num_heads
        self.d_out = d_out
        self.head_dim = d_out // num_heads
        self.dropout = nn.Dropout(dropout)
        self.out_proj = nn.Linear(d_out, d_out)
        self.register_buffer('mask', torch.triu(torch.ones(context_length, context_length), diagonal = 1))
    def forward(self, x):
        b, num_tokens, d_in = x.shape  # input tensor ->[batchsize, num_tokens, input_embedding_shape]
        keys = self.W_key(x)
        queries = self.W_query(x)
        values = self.W_value(x)

        keys = keys.view(b, num_tokens, self.num_heads, self.head_dim)
        queries = queries.view(b, num_tokens, self.num_heads, self.head_dim)
        values = values.view(b, num_tokens, self.num_heads, self.head_dim)

        keys = keys.transpose(1,2)
        queries = queries.transpose(1,2)
        values = values.transpose(1,2)


        attn_scores = queries @ keys.transpose(2,3)
        attn_scores.masked_fill(self.mask.bool()[:num_tokens,:num_tokens], -torch.inf)

        attn_weights = torch.softmax(attn_scores/keys.shape[-1]**0.5, dim = -1)
        attn_weights = self.dropout(attn_weights)
        context_vec = attn_weights@values
        context_vec = context_vec.transpose(1,2)  # b, num_tokens, num_heads, head_dim

        context_vec = context_vec.contiguous().view(b, num_tokens, self.d_out)

        context_vec = self.out_proj(context_vec) # optional projection step

        return context_vec

In [105]:
torch.manual_seed(123)
context_length = inputs.shape[0]
batch = torch.stack((inputs, inputs), dim = 0)
d_in, d_out = 3,4
num_heads = 2
mha = MultiHeadAttention(d_in, d_out, num_heads, context_length, dropout = 0.0)
context_vecs = mha(batch)

In [107]:
context_vecs

tensor([[[-0.0109,  0.3022, -0.0690, -0.3532],
         [-0.0126,  0.2992, -0.0689, -0.3499],
         [-0.0125,  0.2992, -0.0689, -0.3500],
         [-0.0131,  0.2996, -0.0689, -0.3493],
         [-0.0125,  0.3007, -0.0690, -0.3506],
         [-0.0132,  0.2990, -0.0689, -0.3490]],

        [[-0.0109,  0.3022, -0.0690, -0.3532],
         [-0.0126,  0.2992, -0.0689, -0.3499],
         [-0.0125,  0.2992, -0.0689, -0.3500],
         [-0.0131,  0.2996, -0.0689, -0.3493],
         [-0.0125,  0.3007, -0.0690, -0.3506],
         [-0.0132,  0.2990, -0.0689, -0.3490]]], grad_fn=<ViewBackward0>)